### ISSUE TITLE
Approve IP NFT transfer on completed exchange

### ISSUE THREAD

**Issue by davebryson** [synbionet/fair-exchange#1]
A seller deploys an IP NFT (ERC 1155) before creating an offer.  The router will check to make sure the caller owns the NFT and has sufficient balance of `tokenId` that's specified in the offer. 

From a UX perspective, what's the best way to have the seller approve the exchange to transfer the IP NFT to the buyer on a completed exchange?

**Comment by davebryson** [comment]
For now, the easiest approach would be to have the seller approve the exchange to transfer on their behalf outside of the protocol and before creating an offer.

But if part of finalizing an exchange is to transfer the asset from seller to buyer, what if the seller disapproves the exchange before the finalize step?  This could lock-up funds for both parties

**Comment by pwoleary** [comment]
Good point, Dave. I'm going to have to think about this one.

**Comment by pwoleary** [comment]
@davebryson what if ownership of the underlying token(s) is given to the exchange when the offer is made? That would prevent this kind of behavior, no? And make it impossible to create multiple offers that correlate to the same underlying token(s)?
